In [1]:
import torch 

x = torch.zeros([3,3])

In [12]:
import numpy as np

In [5]:
x = torch.ones(3,3,dtype=torch.int16)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [7]:
y = x

torch.mul(x,y)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [9]:
x[0,0].item()

1

In [10]:
x.numpy()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [13]:
b  = np.array([1,1])

In [14]:
b

array([1, 1])

In [17]:
c = torch.tensor(b)
c

tensor([1, 1])

In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device)
    print(x)

Backpropagation 

In [19]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0,requires_grad=True)

In [20]:
y_hat = w*x
s = y-y_hat
loss = s**2
loss.backward()  # backpropagation 

In [21]:
w.grad

tensor(-2.)